<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\Common.Dotnet.Analyzers.props" />
    <Import Project="..\Common.Dotnet.CsWinRT.props" />

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Platforms>x64</Platforms>
    </PropertyGroup>

</Project>
