using System.Collections.Immutable;
using FancyMouse.Win32Gen.NativeMethods;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;

namespace FancyMouse.Win32Gen.Generators;

/// <summary>
/// Shared plumbing for <see cref="Win32AttributeGenerator"/>,
/// <see cref="Win32FrameworkGenerator"/>, and <see cref="Win32FunctionGenerator"/> -
/// each is its own <see cref="IIncrementalGenerator"/> (so each kind of
/// generated output - attributes, framework types, api wrappers - is
/// independently decoupled and can be reasoned about on its own), but all
/// three still emit into the same single <c>{RootNamespace}.Win32Gen</c>
/// namespace, so a consuming project only ever needs one <c>using</c> to
/// see all of it. Only the generated *files* are organised into separate
/// folders (Attributes/Framework/Functions) for on-disk navigability.
/// </summary>
internal static class Win32GeneratorHelpers
{
    private const string DefaultRootNamespace = "GeneratedWin32Interop";
    public const string NamespaceSuffix = "Win32Gen";

    public static IncrementalValueProvider<string> GetRootNamespace(IncrementalGeneratorInitializationContext context)
        => context.AnalyzerConfigOptionsProvider
            .Select(static (options, _) => Win32GeneratorHelpers.ResolveRootNamespace(options));

    public static IncrementalValueProvider<ImmutableArray<NativeMethodsEntry>> GetEntries(IncrementalGeneratorInitializationContext context)
    {
        var nativeMethodTxts = NativeMethodHelper.DiscoverNativeMethodTxts(context);

        return nativeMethodTxts
            .Select(static (file, ct) => NativeMethodsTxtParser.Parse(file, ct).ToImmutableArray())
            .Collect()
            .Select(static (lists, _) => lists.SelectMany(list => list).ToImmutableArray());
    }

    public static string BuildFrameworkFileSource(string rootNamespace, string fragment)
        => $$"""
            // <auto-generated/>
            #nullable enable

            namespace {{rootNamespace}}.{{Win32GeneratorHelpers.NamespaceSuffix}};

            {{fragment}}

            """;

    public static string BuildClassSource(string rootNamespace, string className, IEnumerable<ApiWrapperTemplate> templates)
    {
        var methods = string.Join("\n\n", templates.Select(template => Win32GeneratorHelpers.Indent(template.MethodSource)));

        return $$"""
            // <auto-generated/>
            #nullable enable

            using System.Drawing;
            using System.Runtime.InteropServices;

            using Windows.Win32;
            using Windows.Win32.Foundation;
            using Windows.Win32.Graphics.Gdi;
            using Windows.Win32.UI.HiDpi;
            using Windows.Win32.UI.Input.KeyboardAndMouse;
            using Windows.Win32.UI.Shell;
            using Windows.Win32.UI.WindowsAndMessaging;

            namespace {{rootNamespace}}.{{Win32GeneratorHelpers.NamespaceSuffix}};

            internal static partial class {{className}}
            {
            {{methods}}
            }

            """;
    }

    private static string ResolveRootNamespace(AnalyzerConfigOptionsProvider options)
        => options.GlobalOptions.TryGetValue("build_property.RootNamespace", out var value) && !string.IsNullOrEmpty(value)
            ? value
            : Win32GeneratorHelpers.DefaultRootNamespace;

    private static string Indent(string source)
    {
        var lines = source.Replace("\r\n", "\n").Trim('\n').Split('\n');
        return string.Join("\n", lines.Select(line => line.Length == 0 ? line : "    " + line));
    }
}
