<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\Common.Dotnet.Analyzers.props" />
    <Import Project="..\Common.Dotnet.CsWin32.props" />
    <Import Project="..\Common.Dotnet.props" />

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Platforms>x64</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="images\icon.ico" />
        <EmbeddedResource Include="images\icon.ico" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\FancyMouse.Models\FancyMouse.Models.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.Drawing.Common" Version="10.0.5" />
    </ItemGroup>
</Project>
