<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <PropertyGroup>
    <!--
      change CsWin32Enabled to "true" to regenerate Win32 bindings in the "Generated" folder
      (see Common.CsWin32.props for details)
    -->
    <CsWin32Enabled>false</CsWin32Enabled>
  </PropertyGroup>
  <Import Project="..\Common.CsWin32.props" />

  <ItemGroup>
    <None Remove="images\icon.ico" />
    <EmbeddedResource Include="images\icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FancyMouse.Models\FancyMouse.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="10.0.5" />
    <PackageReference Update="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.201">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Update="StyleCop.Analyzers" Version="1.2.0-beta.507">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Generated\" />
  </ItemGroup>
</Project>
