using System.Diagnostics.CodeAnalysis;
using System.Runtime.InteropServices;
using static FancyMouse.NativeMethods.Core;

namespace FancyMouse.NativeMethods;

internal static partial class User32
{
    /// <summary>
    /// Contains information about a simulated message generated by an input device
    /// other than a keyboard or mouse.
    /// </summary>
    /// <remarks>
    /// See https://learn.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-hardwareinput
    /// </remarks>
    [SuppressMessage("SA1307", "SA1307:AccessibleFieldsMustBeginWithUpperCaseLetter", Justification = "Parameter name matches Win32 api")]
    [StructLayout(LayoutKind.Sequential)]
    internal readonly struct HARDWAREINPUT
    {
        public readonly DWORD uMsg;
        public readonly WORD wParamL;
        public readonly WORD wParamH;

        public HARDWAREINPUT(
            DWORD uMsg,
            WORD wParamL,
            WORD wParamH)
        {
            this.uMsg = uMsg;
            this.wParamL = wParamL;
            this.wParamH = wParamH;
        }
    }
}
