<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\Common.Dotnet.Analyzers.props" />
    <Import Project="..\Common.Dotnet.CsWin32.props" />
    <Import Project="..\Common.Dotnet.props" />

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Platforms>x64</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\FancyMouse.Common\FancyMouse.Common.csproj" />
    </ItemGroup>

</Project>
